### ISSUE TITLE
[Compatability]

### ISSUE THREAD

**Issue by mflaherty97** [jsavko/boss-splash#12]
This module doesn't seem to be currently compatible with "Monk's Common Display"

I use a game table with a TV set in it for my players. With Monk's Common Display I have "Hide UI" turned on for the table screen. This way the players only see the map and none of the UI. However, it seems that the Boss Splash Screen is considered to be "UI" by "Monk's Common Display."

I'm not sure if this is a Monk issue or a you issue, so I'm bringing it up on both repos.

Thank you!

**Comment by jsavko** [comment]
Boss Spash uses the application layer, so anything they hides the application layer will prevent the display.
