### ISSUE TITLE
[Enhancement] Choosing which sound to play

### ISSUE THREAD

**Issue by SpectreWulf** [jsavko/boss-splash#13]
First of all excellent immersion module! 

Sometimes I would love to show Boss Splash even for minor deadly enemies / other reminders.

Can we have the option to assign multiple sound files and when choosing to splash the token, show a pop up to choose which sound to play before displaying the Boss Splash Animation?

**Comment by jsavko** [comment]
This could be done via macro or using the script API available.
```game.bossSplash.splashBoss({sound:"/path/to/sound/file"})``` as a script macro will play whatever sound you have specified while using the targeted token for the img, and name.  
You can find the full allowed arguments here
https://github.com/jsavko/boss-splash/blob/main/README.md

**Comment by SpectreWulf** [comment]
> This could be done via macro or using the script API available. `game.bossSplash.splashBoss({sound:"/path/to/sound/file"})` as a script macro will play whatever sound you have specified while using the targeted token for the img, and name. You can find the full allowed arguments here https://github.com/jsavko/boss-splash/blob/main/README.md

Thanks for the quick reply!

I will have a look at it!
