### ISSUE TITLE
🔉 Option to have the animation start delayed..

### ISSUE THREAD

**Issue by Abourass** [jsavko/boss-splash#14]
Hello, wonderful module; however, I'd love to use a nice musical singer like: 
`https://pixabay.com/sound-effects/horror-hit-logo-142395/`
But when you use something like this, the animation starts before the dramatic part of the sting happens. I'd love an options to delay the animation starting (in milliseconds) so that when I intro a boss, I can hit peak drama for the scene. 

Thanks!

**Comment by jsavko** [comment]
It’s a good idea. I have implemented it in my local dev build and will be part of the next release that includes v12 support
