### ISSUE TITLE
[Enhancement] Splash in with custom image

### ISSUE THREAD

**Issue by picollo-24** [jsavko/boss-splash#17]
I would love to have option to use Boss Splash with something like Persona 5 cut-ins like in the video below:
https://www.youtube.com/watch?app=desktop&v=FB5fG_CIYQ8

This could be hard to have done programatically, exactly as it is, but maybe just simple option to define cut-in graphic per token, and when you use the splash option, it would just show art on the screen, then push it from the screen to the right to disappear?

**Comment by jsavko** [comment]
I added the video option for this for another user.  I looked into doing it programmatically and it's not worth the time invested to get it to work correctly.   I do however accept pull requests if you want to spend that time doing it
