### ISSUE TITLE
Option to choose whether boss splash shows token art or character art

### ISSUE THREAD

**Issue by Tyranness** [jsavko/boss-splash#18]
Hi, I think adding a feature in module config for whether or not the token art or character art is used would be really nice, I normally use the character art for the icon (because it doesn't give me an option to have separate icon art ;-;) rather then the full body image due to foundry formatting and the token art for the full body image and I figure everyone treats them differently formatting wise.

**Comment by jsavko** [comment]
I accept pull requets

**Comment by jsavko** [comment]
> rather then the full body image due to foundry formatting and the token art

You can edit the prototype token of each actor to assign different art to the token from the actor.
