### ISSUE TITLE
[Enhancment] Option to display token name rather than actor name

### ISSUE THREAD

**Issue by Dom-Odyssey** [jsavko/boss-splash#19]
Is there an option for the slash screen to use the current token name rather than calling from the actor.? if not is this something can be added? If this is already an option can the readme be updated to note what string should be used to call token name{{tokenname?}} instead of actor name{{name}}.

**Comment by jsavko** [comment]
The macro options allow you to define any name

**Comment by jsavko** [comment]
Added the option to use {{actor.name}} or {{token.name}} to both overrides and settings.

**Comment by Dom-Odyssey** [comment]
Thank you very much, I really appreciate it.
