### ISSUE TITLE
[Enhancement]Changing the font ?

### ISSUE THREAD

**Issue by Wotn9** [jsavko/boss-splash#2]
Just found out that module, made me laugh quite a lot, I love it it's epic. But will there be a setting to change the font later ?

**Comment by jsavko** [comment]
Font configuration is in the next build which is in the testing phase. It should be released tomorrow

**Comment by Armandeus66** [comment]
Thanks for adding this feature.
I can't seem to get it to work. The pulldown menu shows no fonts. I have set up a few fonts in the Foundry core settings.
How do you set the banner font for this module?

**Comment by jsavko** [comment]
Looks like my last update created a bug with the font list. It will be fixed in 1.1.5 which I will push in the next 20 minutes
