### ISSUE TITLE
Splash sound is not playing

### ISSUE THREAD

**Issue by LeoAndrade-DungeonMaster** [jsavko/boss-splash#25]
Splash sound is not playing on Foundry 11.314

**Comment by jsavko** [comment]
What version of Boss Splash?

**Comment by LeoAndrade-DungeonMaster** [comment]
Boss Splash is on version 1.1.11

Em qui., 18 de jul. de 2024, 13:02, jsavko ***@***.***>
escreveu:

**Comment by jsavko** [comment]
Downgrade to 1.1.7 which is the last version for foundry v11 https://github.com/jsavko/boss-splash/releases/download/1.1.7/module.json

**Comment by LeoAndrade-DungeonMaster** [comment]
Ok, thanks for the help

Em qui., 18 de jul. de 2024, 15:31, jsavko ***@***.***>
escreveu:
