### ISSUE TITLE
[Enhancement] Ability to leave on until GM clicks (or right clicks) to remove image

### ISSUE THREAD

**Issue by MightyMushka** [jsavko/boss-splash#3]
Absolutely love the module! I think it's great not just for boss splash art but NPCs too. I was wondering if there could be a toggleable option to enable dismissing only when the GM commands (such as with a left or right click on the image), which could then be sent to tell the connected client to close theirs instead of a universal timer.

Thanks again for the awesome module!

**Comment by jsavko** [comment]
Planned for 1.1.0 release.  
Two new options added to the macro route, 

Open boss splash with no dismisal timer 
```game.bossSplash.splashBoss({timer:0})```

Close all open splash screens for all players 
```game.bossSplash.splashBoss({close:true})```

Working on figuring out a good place to put an UI element to allow players to close the splash screen themselves early.
