### ISSUE TITLE
[Enhancement] Add animation to NPC name

### ISSUE THREAD

**Issue by weepingminotaur** [jsavko/boss-splash#4]
Would be sweet to be able to have the NPC's name dripping blood or in swirling shadow or something like that. :D Don't know if that's possible but I figured it couldn't hurt to ask.

**Comment by jsavko** [comment]
This could be done with a custom CSS module or by creating a custom template.  
Here is an example of CSS blood drips 
https://codepen.io/bpopek/pen/eYJYzPV
