### ISSUE TITLE
[Enhancement] Custom Splash to any character

### ISSUE THREAD

**Issue by bookguysmith** [jsavko/boss-splash#5]
Firstly, love the module. My players love these little flourishes. Suggestions for improvements: 

1) Increase / change display font size
2) Custom splashes for NPCs (or bosses) based on affiliation or faction, which could include an additional image for banner or insignia and then a pre-defined scheme (colors, sounds, fonts) for said grouping. 
or
3) A totally customizable splash for every new actor. For instance, enter the Actor ID, create the scheme, and save it to a journal for reference (Not sure how the data is stored. I can't program...obviously).

Keep up the amazing work!

**Comment by jsavko** [comment]
Customizing font size is an obvious improvement I should have included in the last update when I allowed custom font selection. I will add this to the next update.

**Comment by jsavko** [comment]
Fontsize has been added  to the settings menu and overrides as of this morning's 1.1.1 release
