### ISSUE TITLE
[Enhancement] Is it possible to add a setting so that players can also run splash art?

### ISSUE THREAD

**Issue by rlavkvmflzk** [jsavko/boss-splash#8]
Your great ideas are making the game more fun to play. Thank you. 
By the way, could you please add a setting to allow splash art to run even if you are not a GM? I want my players to be able to use splash art under certain conditions. I would appreciate it if you could.

**Comment by jsavko** [comment]
I've went ahead and made an option to set account level to be able to use Boss Splash.  This allows splashing from the TokenHud, Actor Context, and Macro.  

![image](https://github.com/jsavko/boss-splash/assets/192591/bbaacebe-52c4-4a3e-a692-3cd99a41ba6c)

It will be included in the next update
